# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('index', models.CharField(max_length=120, verbose_name='Index')),
                ('value', models.FloatField(verbose_name='Value')),
                ('month', models.CharField(max_length=60, verbose_name='Month')),
            ],
        ),
    ]
